# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 80abde36bf908fcbf7cac870003370e1d20ec10de7801051dbe6dc07994d5e04c15e6e418ff87eb1947ce54a57d6996d6ac07a9e53ee3950cc59220c9d0f23a0

test:
  secret_key_base: 86311fa498aab0cc7bdcae57f5a5ca7fe6237fffd5e4572a409824696a4bd72ccb86c256d8066385a5b89da79000e4f8ac2471c859b61c1c197cf3e7bf37e50c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
